[package]
name = "pro2-vault-entry"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rpassword = "7.3"
aes-gcm = "0.10"
aes = "0.8"
rand = "0.8"
sha2 = "0.10"
pbkdf2 = "0.12"